name: React Build

on: [pull_request]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: Show folders
        run: ls
        
      - name: Move to clientapp folder
        run: cd eShop.API/clientapp

      - name: Install dependencies
        run: |
          ls
          yarn

      - name: Build
        run: |
          ls
          yarn build

      - name: Test
        run: |
          ls
          yarn test --watchAll=false