name: React Build

on: [pull_request]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn
        with:
          path: eshop.api/clientapp/

      - name: Build
        run: yarn build
        with:
          path: eshop.api/clientapp/

      - name: Test
        run: yarn test --watchAll=false
        with:
          path: eshop.api/clientapp/